//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidiyalAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public int CenterID { get; set; }
        public string CenterName { get; set; }
        public string CenterHeadName { get; set; }
        public string CenterAddressLine1 { get; set; }
        public string CenterAddressLine2 { get; set; }
        public string City { get; set; }
        public string CenterContactNumber { get; set; }
        public string CenterStartDate { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
