//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidiyalAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string YearOfBirth { get; set; }
        public string KYCDetails { get; set; }
        public string AdharcardDetails { get; set; }
        public string VoterID { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string ContactNumber3 { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string PermanentAddressLine1 { get; set; }
        public string PermanentAddressLine2 { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentPinCode { get; set; }
        public string TemporaryAddressLine1 { get; set; }
        public string TemporaryAddressLine2 { get; set; }
        public string TemporaryCity { get; set; }
        public string TemporaryPinCode { get; set; }
        public string JoiningDate { get; set; }
        public int IsActive { get; set; }
    }
}
